language: node_js
before_install:
- export TZ=Europe/Berlin
script: npm run test:coverage
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: 7c9a0965d354a5ccb123a32279450119b35157ae19b111cb9f2ab1a81eecfba8
